environment:

  matrix:

    - PYTHON: "C:\\Python36-x64"

install:
  - "%PYTHON%\\python.exe -m pip install wheel"

build: off

test_script:
   - "%PYTHON%\\python.exe --version"
#  - "build.cmd %PYTHON%\\python.exe setup.py test"

after_test:
  - "build.cmd %PYTHON%\\python.exe setup.py bdist_wheel"

artifacts:
  - path: dist\*

#on_success:
#  You can use this step to upload your artifacts to a public website.
#  See Appveyor's documentation for more details. Or you can simply
#  access your wheels from the Appveyor "artifacts" tab for your build.