environment:

  matrix:

    - PYTHON: "C:\\Python36-x64"

install:
  - "%PYTHON%\\python.exe -m pip install -r requirements.txt"
  - "%PYTHON%\\python.exe -m pip install -r requirements-dev.txt"

build: off

test_script:
  - "build.cmd %PYTHON%\\python.exe setup.py test"

after_test:
  - "build.cmd %PYTHON%\\python.exe setup.py bdist_wheel"
  - "build.cmd %PYTHON%\\Scripts\\pyinstaller --onefile topN/top_n_average_by_county_from_top_n_global.py --name topN"

artifacts:
  - path: dist\*

#on_success:
#  You can use this step to upload your artifacts to a public website.
#  See Appveyor's documentation for more details. Or you can simply
#  access your wheels from the Appveyor "artifacts" tab for your build.